export const categoryObject = {
  'All Class': {},
  Major: {
    'College of Nursing': [],
    'Korea University Business School': [],
    'College of Engineering': [],
    'College of International Studies': [],
    'School of Art & Design': [],
    'College of Liberal Arts': [],
    'School of Media & Communication': [],
    'College of Health Sciences': [],
    'College of Education': [],
    'College of Life Sciences and Biotechnology': [],
    'School of Smart Mobility': [],
    'Division of Smart Security': [],
    'School of Psychology': [],
    'College of Medicine': [],
    'College of Science': [],
    'College of Political Science & Economics': [],
    'College of Informatics': [],
    'KU-KIST Converging Science and Technology': [],
    'School of Law': [],
    'Center for Cooperative Education': [],
  },
  'Academic Foundations': {
    'College of Nursing': [],
    'Korea University Business School': [],
    'College of Engineering': [],
    'College of International Studies': [],
    'School of Art & Design': [],
    'College of Liberal Arts': [],
    'School of Media & Communication': [],
    'College of Health Sciences': [],
    'College of Education': [],
    'College of Life Sciences and Biotechnology': [],
    'School of Smart Mobility': [],
    'Division of Smart Security': [],
    'School of Psychology': [],
    'College of Medicine': [],
    'College of Science': [],
    'College of Political Science & Economics': [],
    'College of Informatics': [],
    'KU-KIST Converging Science and Technology': [],
    'School of Law': [],
    'Center for Cooperative Education': [],
  },
  'General Studies': [
    'ACADEMIC ENGLISH',
    'COLLEGE WRITING',
    'DS/AI',
    'Digital Innovation & Humanity',
    'EXPLORATION OF THE ACADEMIC WORLD I',
    'EXPLORATION OF THE ACADEMIC WORLD II',
    'Electives',
    'Electives(Basic Sciences)',
    'Electives(Foreign Languages)',
    'Ethics & Philosophy',
    'Freshman Seminar',
    'GLOBAL ENGLISH',
    'History',
    'Literature & Art',
    'Military Studies',
    'Quantitative Analysis',
    'Required',
    'Science & Technology',
    'Sociological Studies',
    'World Cultures',
  ],
}
