export const categoryObject: { [key in string]: string[] } = {
  'College of Nursing': ['Department of Nursing'],
  'Korea University Business School': ['Department of Business Administration'],
  'College of Engineering': [
    'College of Engineering',
    'Department of Mechanical Engineering',
    'School of Industrial and Management Engineering',
    'Department of Materials Science and Engineering',
    'School of Electrical Engineering',
    'School of Civil, Environmental and Architectural Engineering',
    'Department of Architecture',
    'Technology Entrepreneurship Major',
    'Department of Semiconductor Engineering',
    'New Energy Industry',
    'Department of Integrative Energy Engineering',
    'Department of Communications Engineering',
    'Department of Chemical and Biological Eng',
  ],
  'College of International Studies': [
    'Division of International Studies',
    'Division of Global Korean Studies',
    'Global Korean Studies Interdisciplinary Major',
  ],
  'School of Art & Design': ['School of Art & Design'],
  'College of Liberal Arts': [
    'College of Liberal Arts',
    'EML(Emerging Market and Latin America)',
    'Global Leader for East Asian Century',
    'LB&C(Language, Brain & Computer)',
    'Department of Korean Language and Literature',
    'Department of Russian Language and Literature',
    'Department of German Language and Literature',
    'Department of French Language and Literature',
    'Department of History',
    'Department of Sociology',
    'Department of Spanish Language and Literature',
    'Department of Linguistics',
    'Department of English Language and Literature',
    'Medical Humanities',
    'Interdisciplinary Digital Literary Studies',
    'Humanities and Creative Industry',
    'Humanities and Justice',
    'Department of Japanese Language and Literature',
    'Department of Chinese Language and Literature',
    'Department of Philosophy',
    'Unification and International Peace',
    'Department of Korean History',
    'Department of Sinographic Literatures',
  ],
  'School of Media & Communication': ['School of Media & Communication'],
  'College of Health Sciences': [
    'School of Biosystems and Biomedical Sciences',
    'School of Biomedical Engineering',
    'Division of Health Policy and Management',
    'School of Health and Environmental Science',
  ],
  'College of Education': [
    'College of Education',
    'Department of Home Economics Education',
    'Department of Education',
    'Department of Korean Language Education',
    'Multicultural Korean Education',
    'Department of Mathematics Education',
    'Department of History Education',
    'Department of English Language Education',
    'Department of Geography Education',
    'Department of Physical Education',
    'Fashion Design and Merchandising',
  ],
  'College of Life Sciences and Biotechnology': [
    'Division of Biotechnology',
    'College of Life Sciences',
    'Division of Life Sciences',
    'Division of Environmental Science and Ecological Engineering',
    'Ecological Landscape Architecture',
    'Division of Food Bioscience and Technology',
    'Department of Food and Resource Economics',
  ],
  'School of Smart Mobility': ['School of Smart Mobility'],
  'Division of Smart Security': [
    'Data Protection and Privacy',
    'Department of Cyber Defense',
    'Division of Smart Security',
  ],
  'School of Psychology': ['School of Psychology'],
  'College of Medicine': ['Department of Pre-Medical Course', 'Department of Medical Science'],
  'College of Science': [
    'College of Science',
    'Department of Physics',
    'Department of Mathematics',
    'Department of Earth and Environmental Sciences',
    'Department of Chemistry',
  ],
  'College of Political Science & Economics': [
    'College of Political Science and Economics',
    'Department of Economics',
    'Financial Engineering',
    'Department of Political Science and International Relations',
    'Department of Statistics',
    'Department of Public Administration',
  ],
  'College of Informatics': [
    'Brain and Cognitive Sciences',
    'Department of Data Science',
    'Software Technology & Entrepreneurship Program',
    'Interdisciplinary Major in Artificial Intelligence',
    'Information Security',
    'Department of Computer Science and Engineering',
  ],
  'KU-KIST Converging Science and Technology': ['Medical Convergence Engineering'],
  'School of Law': ['School of Law'],
  'Center for Cooperative Education': ['Center for Cooperative Education'],
}

// export const generalStudies = [
//   'ACADEMIC ENGLISH',
//   'COLLEGE WRITING',
//   'DS/AI',
//   'Digital Innovation & Humanity',
//   'EXPLORATION OF THE ACADEMIC WORLD I',
//   'EXPLORATION OF THE ACADEMIC WORLD II',
//   'Electives',
//   'Electives(Basic Sciences)',
//   'Electives(Foreign Languages)',
//   'Ethics & Philosophy',
//   'Freshman Seminar',
//   'GLOBAL ENGLISH',
//   'History',
//   'Literature & Art',
//   'Military Studies',
//   'Quantitative Analysis',
//   'Required',
//   'Science & Technology',
//   'Sociological Studies',
//   'World Cultures',
// ]
