/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AcademicSchedule
 */
export interface AcademicSchedule {
  /**
   * 행사/일정 id
   * @type {number}
   * @memberof AcademicSchedule
   */
  id: number
  /**
   * 행사/일정 제목
   * @type {string}
   * @memberof AcademicSchedule
   */
  title: string
  /**
   * 행사/일정 설명
   * @type {string}
   * @memberof AcademicSchedule
   */
  description: string
  /**
   * 시작 날짜
   * @type {string}
   * @memberof AcademicSchedule
   */
  startDate: string
  /**
   * 시작 요일
   * @type {string}
   * @memberof AcademicSchedule
   */
  startDay: string
  /**
   * 종료 날짜
   * @type {string}
   * @memberof AcademicSchedule
   */
  endDate: string
  /**
   * 종료 요일
   * @type {string}
   * @memberof AcademicSchedule
   */
  endDay: string
}
