/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BoardInfo
 */
export interface BoardInfo {
  /**
   * 게시판 고유 ID
   * @type {number}
   * @memberof BoardInfo
   */
  id: number
  /**
   * 게시판 이름
   * @type {string}
   * @memberof BoardInfo
   */
  name: string
  /**
   * 게시판 설명
   * @type {string}
   * @memberof BoardInfo
   */
  description: string
}
