/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChangePasswordRequestDto
 */
export interface ChangePasswordRequestDto {
  /**
   * 변경하고자 하는 비밀번호
   * @type {string}
   * @memberof ChangePasswordRequestDto
   */
  newPassword: string
}
