/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Character } from './character'

/**
 *
 * @export
 * @interface CommunityUser
 */
export interface CommunityUser {
  /**
   * 사용자, 익명이면 \"Anonymous\", 탈퇴했으면 \"Deleted\"
   * @type {string}
   * @memberof CommunityUser
   */
  username: string
  /**
   * 사용자가 익명인지
   * @type {boolean}
   * @memberof CommunityUser
   */
  isAnonymous: boolean
  /**
   * 사용자가 탈퇴된 유저인지
   * @type {boolean}
   * @memberof CommunityUser
   */
  isDeleted: boolean
  /**
   * 사용자 캐릭터
   * @type {Character}
   * @memberof CommunityUser
   */
  character: Character
}
