/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CommonCourseResponseDtoDetails
 */
export interface CommonCourseResponseDtoDetails {
  /**
   *
   * @type {string}
   * @memberof CommonCourseResponseDtoDetails
   */
  day?: string
  /**
   *
   * @type {string}
   * @memberof CommonCourseResponseDtoDetails
   */
  startTime?: string
  /**
   *
   * @type {string}
   * @memberof CommonCourseResponseDtoDetails
   */
  endTime?: string
  /**
   *
   * @type {string}
   * @memberof CommonCourseResponseDtoDetails
   */
  classroom?: string
}
