/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonCourseResponseDtoDetails } from './common-course-response-dto-details'

/**
 *
 * @export
 * @interface CommonCourseResponseDto
 */
export interface CommonCourseResponseDto {
  /**
   * ID
   * @type {number}
   * @memberof CommonCourseResponseDto
   */
  id: number
  /**
   * 교수 이름
   * @type {string}
   * @memberof CommonCourseResponseDto
   */
  professorName: string
  /**
   * 강의 구분
   * @type {string}
   * @memberof CommonCourseResponseDto
   */
  category: string
  /**
   * 단과대 이름
   * @type {string}
   * @memberof CommonCourseResponseDto
   */
  college: string
  /**
   * 강의명
   * @type {string}
   * @memberof CommonCourseResponseDto
   */
  courseName: string
  /**
   * 학수 번호
   * @type {string}
   * @memberof CommonCourseResponseDto
   */
  courseCode: string
  /**
   * 학점
   * @type {number}
   * @memberof CommonCourseResponseDto
   */
  credit: number
  /**
   * 학과 이름
   * @type {string}
   * @memberof CommonCourseResponseDto
   */
  major: string
  /**
   * 교환학생 수강 가능 여부
   * @type {boolean}
   * @memberof CommonCourseResponseDto
   */
  hasExchangeSeat: boolean
  /**
   * 연도
   * @type {string}
   * @memberof CommonCourseResponseDto
   */
  year: string
  /**
   * 학기
   * @type {string}
   * @memberof CommonCourseResponseDto
   */
  semester: string
  /**
   * 강의계획서 url
   * @type {string}
   * @memberof CommonCourseResponseDto
   */
  syllabus: string
  /**
   * 강의평점
   * @type {number}
   * @memberof CommonCourseResponseDto
   */
  totalRate: number
  /**
   * 강의 세부사항
   * @type {Array<CommonCourseResponseDtoDetails>}
   * @memberof CommonCourseResponseDto
   */
  details: Array<CommonCourseResponseDtoDetails>
}
