/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CourseReviewResponseDto
 */
export interface CourseReviewResponseDto {
  /**
   * id
   * @type {number}
   * @memberof CourseReviewResponseDto
   */
  id: number
  /**
   * 작성자
   * @type {string}
   * @memberof CourseReviewResponseDto
   */
  reviewer: string
  /**
   * 작성일
   * @type {string}
   * @memberof CourseReviewResponseDto
   */
  createdAt: string
  /**
   * 강의 평점
   * @type {number}
   * @memberof CourseReviewResponseDto
   */
  rate: number
  /**
   * 수업 난이도
   * @type {number}
   * @memberof CourseReviewResponseDto
   */
  classLevel: number
  /**
   * 팀 프로젝트 난이도
   * @type {number}
   * @memberof CourseReviewResponseDto
   */
  teamProject: number
  /**
   * 학습량
   * @type {number}
   * @memberof CourseReviewResponseDto
   */
  amountLearned: number
  /**
   * 교수님 강의력
   * @type {number}
   * @memberof CourseReviewResponseDto
   */
  teachingSkills: number
  /**
   * 출석체크 여부
   * @type {number}
   * @memberof CourseReviewResponseDto
   */
  attendance: number
  /**
   * 추천수
   * @type {number}
   * @memberof CourseReviewResponseDto
   */
  recommendCount: number
  /**
   * 강의평 남기기
   * @type {string}
   * @memberof CourseReviewResponseDto
   */
  textReview: string
  /**
   * 해당 강의 교수님 성함
   * @type {string}
   * @memberof CourseReviewResponseDto
   */
  professorName: string
  /**
   * 해당 강의 연도
   * @type {string}
   * @memberof CourseReviewResponseDto
   */
  year: string
  /**
   * 해당 강의 학기
   * @type {string}
   * @memberof CourseReviewResponseDto
   */
  semester: string
  /**
   * 해당 강의 학수번호
   * @type {string}
   * @memberof CourseReviewResponseDto
   */
  courseCode: string
  /**
   * 강의평 작성한 유저 ID
   * @type {number}
   * @memberof CourseReviewResponseDto
   */
  userId: number
}
