/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateReportRequestDto
 */
export interface CreateReportRequestDto {
  /**
   * 게시글 ID
   * @type {number}
   * @memberof CreateReportRequestDto
   */
  postId: number
  /**
   * 댓글 ID (댓글 신고일 경우 존재, 게시글 신고일 경우 null
   * @type {number}
   * @memberof CreateReportRequestDto
   */
  commentId?: number
  /**
   * 신고 사유
   * @type {string}
   * @memberof CreateReportRequestDto
   */
  reason: string
}
