/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateCourseReviewRequestDto
 */
export interface CreateCourseReviewRequestDto {
  /**
   * 강의 평점
   * @type {number}
   * @memberof CreateCourseReviewRequestDto
   */
  rate: number
  /**
   * 수업 난이도
   * @type {number}
   * @memberof CreateCourseReviewRequestDto
   */
  classLevel: number
  /**
   * 팀 프로젝트 난이도
   * @type {number}
   * @memberof CreateCourseReviewRequestDto
   */
  teamProject: number
  /**
   * 학습량
   * @type {number}
   * @memberof CreateCourseReviewRequestDto
   */
  amountLearned: number
  /**
   * 교수님 강의력
   * @type {number}
   * @memberof CreateCourseReviewRequestDto
   */
  teachingSkills: number
  /**
   * 출석체크 여부
   * @type {number}
   * @memberof CreateCourseReviewRequestDto
   */
  attendance: number
  /**
   * 강의평 남기기
   * @type {string}
   * @memberof CreateCourseReviewRequestDto
   */
  textReview: string
  /**
   * 연도
   * @type {string}
   * @memberof CreateCourseReviewRequestDto
   */
  year: string
  /**
   * 학기
   * @type {string}
   * @memberof CreateCourseReviewRequestDto
   */
  semester: string
  /**
   * 교수님 성함
   * @type {string}
   * @memberof CreateCourseReviewRequestDto
   */
  professorName: string
  /**
   * 학수번호
   * @type {string}
   * @memberof CreateCourseReviewRequestDto
   */
  courseCode: string
}
