/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateTimetableCourseResponseDto
 */
export interface CreateTimetableCourseResponseDto {
  /**
   * ID
   * @type {number}
   * @memberof CreateTimetableCourseResponseDto
   */
  id: number
  /**
   * 시간표 ID
   * @type {number}
   * @memberof CreateTimetableCourseResponseDto
   */
  timetableId: number
  /**
   * 강의 ID
   * @type {number}
   * @memberof CreateTimetableCourseResponseDto
   */
  courseId: number
}
