/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CursorPageMetaResponseDto
 */
export interface CursorPageMetaResponseDto {
  /**
   * 다음 페이지 존재 여부
   * @type {boolean}
   * @memberof CursorPageMetaResponseDto
   */
  hasNextData: boolean
  /**
   * 다음페이지 조회용 커서, 다음페이지 없으면 null
   * @type {string}
   * @memberof CursorPageMetaResponseDto
   */
  nextCursor: string
}
