/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Event
 */
export interface Event {
  /**
   * 행사/일정 id
   * @type {number}
   * @memberof Event
   */
  id: number
  /**
   * 행사/일정 제목
   * @type {string}
   * @memberof Event
   */
  title: string
  /**
   * 행사/일정 설명
   * @type {string}
   * @memberof Event
   */
  description: string
}
