/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetRecommendClubResponseDto
 */
export interface GetRecommendClubResponseDto {
  /**
   * 동아리명
   * @type {string}
   * @memberof GetRecommendClubResponseDto
   */
  name: string
  /**
   * 동아리 요약
   * @type {string}
   * @memberof GetRecommendClubResponseDto
   */
  summary: string
  /**
   * 동아리 사진 URL
   * @type {string}
   * @memberof GetRecommendClubResponseDto
   */
  imageUrl: string
  /**
   * 동아리 카테고리
   * @type {string}
   * @memberof GetRecommendClubResponseDto
   */
  category: string
}
