/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetCourseInfoByTimetableIdResponseDto } from './get-course-info-by-timetable-id-response-dto'
import { GetScheduleInfoByTimetableIdResponseDto } from './get-schedule-info-by-timetable-id-response-dto'

/**
 *
 * @export
 * @interface GetTimetableByTimetableIdDto
 */
export interface GetTimetableByTimetableIdDto {
  /**
   *
   * @type {Array<GetCourseInfoByTimetableIdResponseDto>}
   * @memberof GetTimetableByTimetableIdDto
   */
  courses?: Array<GetCourseInfoByTimetableIdResponseDto>
  /**
   *
   * @type {Array<GetScheduleInfoByTimetableIdResponseDto>}
   * @memberof GetTimetableByTimetableIdDto
   */
  schedules?: Array<GetScheduleInfoByTimetableIdResponseDto>
  /**
   * 시간표 색상
   * @type {string}
   * @memberof GetTimetableByTimetableIdDto
   */
  color: string
  /**
   * 시간표 이름
   * @type {string}
   * @memberof GetTimetableByTimetableIdDto
   */
  timetableName: string
}
