/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Event } from './event'

/**
 *
 * @export
 * @interface GetDailyCalendarDataResponseDto
 */
export interface GetDailyCalendarDataResponseDto {
  /**
   * 날짜 (AAAA-BB-CC 형식)
   * @type {string}
   * @memberof GetDailyCalendarDataResponseDto
   */
  date: string
  /**
   * 행사/일정 제목
   * @type {Array<Event>}
   * @memberof GetDailyCalendarDataResponseDto
   */
  event: Array<Event>
  /**
   * 행사/일정 개수
   * @type {number}
   * @memberof GetDailyCalendarDataResponseDto
   */
  eventCount: number
}
