/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Comment } from './comment'
import { CommunityUser } from './community-user'
import { Image } from './image'
import { ReactionCount } from './reaction-count'

/**
 *
 * @export
 * @interface GetPostResponseDto
 */
export interface GetPostResponseDto {
  /**
   * 게시글 고유 ID
   * @type {number}
   * @memberof GetPostResponseDto
   */
  id: number
  /**
   * 본인이 작성한 글인지 여부
   * @type {boolean}
   * @memberof GetPostResponseDto
   */
  isMyPost: boolean
  /**
   * 게시글 제목
   * @type {string}
   * @memberof GetPostResponseDto
   */
  title: string
  /**
   * 게시글 내용
   * @type {string}
   * @memberof GetPostResponseDto
   */
  content: string
  /**
   * 게시글 생성 시간
   * @type {string}
   * @memberof GetPostResponseDto
   */
  createdAt: string
  /**
   * 게시글 수정 시간
   * @type {string}
   * @memberof GetPostResponseDto
   */
  updatedAt: string
  /**
   * 게시글을 생성한 사용자
   * @type {CommunityUser}
   * @memberof GetPostResponseDto
   */
  user: CommunityUser
  /**
   * 조회수
   * @type {number}
   * @memberof GetPostResponseDto
   */
  views: number
  /**
   * 스크랩 수
   * @type {number}
   * @memberof GetPostResponseDto
   */
  scrapCount: number
  /**
   * 스크랩 여부
   * @type {boolean}
   * @memberof GetPostResponseDto
   */
  myScrap: boolean
  /**
   * 반응
   * @type {ReactionCount}
   * @memberof GetPostResponseDto
   */
  reactionCount: ReactionCount
  /**
   * 내 반응(없으면 null)
   * @type {number}
   * @memberof GetPostResponseDto
   */
  myReaction: number
  /**
   * 댓글
   * @type {Array<Comment>}
   * @memberof GetPostResponseDto
   */
  comments: Array<Comment>
  /**
   * 첨부 이미지 경로
   * @type {Array<Image>}
   * @memberof GetPostResponseDto
   */
  imageDirs: Array<Image>
}
