/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommunityUser } from './community-user'

/**
 *
 * @export
 * @interface GetCommentResponseDto
 */
export interface GetCommentResponseDto {
  /**
   * 댓글 고유 ID
   * @type {number}
   * @memberof GetCommentResponseDto
   */
  id: number
  /**
   * 삭제된 댓글인지 여부
   * @type {boolean}
   * @memberof GetCommentResponseDto
   */
  isDeleted: boolean
  /**
   * 댓글 생성 시간
   * @type {string}
   * @memberof GetCommentResponseDto
   */
  createdAt: string
  /**
   * 댓글 수정 시간
   * @type {string}
   * @memberof GetCommentResponseDto
   */
  updatedAt: string
  /**
   * 본인이 작성한 댓글인지 여부
   * @type {boolean}
   * @memberof GetCommentResponseDto
   */
  isMyComment: boolean
  /**
   * 게시글 작성자의 댓글인지 여부
   * @type {boolean}
   * @memberof GetCommentResponseDto
   */
  isAuthor: boolean
  /**
   * 댓글 내용
   * @type {string}
   * @memberof GetCommentResponseDto
   */
  content: string
  /**
   * 댓글을 작성한 사용자
   * @type {CommunityUser}
   * @memberof GetCommentResponseDto
   */
  user: CommunityUser
  /**
   * 좋아요 수
   * @type {number}
   * @memberof GetCommentResponseDto
   */
  likeCount: number
  /**
   * 좋아요 눌렀는지 여부
   * @type {boolean}
   * @memberof GetCommentResponseDto
   */
  myLike: boolean
}
