/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReportedComment } from './reported-comment'
import { ReportedPost } from './reported-post'
import { ReportedUser } from './reported-user'

/**
 *
 * @export
 * @interface GetReportResponseDto
 */
export interface GetReportResponseDto {
  /**
   * 신고된 게시글
   * @type {ReportedPost}
   * @memberof GetReportResponseDto
   */
  reportedPost: ReportedPost
  /**
   * 신고된 댓글
   * @type {ReportedComment}
   * @memberof GetReportResponseDto
   */
  reportedComment: ReportedComment
  /**
   * 해당 글에 접수된 신고 횟수
   * @type {number}
   * @memberof GetReportResponseDto
   */
  reportCount: number
  /**
   * 신고된 사용자
   * @type {ReportedUser}
   * @memberof GetReportResponseDto
   */
  reportedUser: ReportedUser
}
