/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetReceivedFriendshipRequestCountDto
 */
export interface GetReceivedFriendshipRequestCountDto {
  /**
   * 전체 받은 친구 요청 개수
   * @type {number}
   * @memberof GetReceivedFriendshipRequestCountDto
   */
  totalCount: number
  /**
   * 확인하지 않은 받은 친구 요청 개수
   * @type {number}
   * @memberof GetReceivedFriendshipRequestCountDto
   */
  unreadCount: number
}
