/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BoardInfo } from './board-info'
import { CursorPageMetaResponseDto } from './cursor-page-meta-response-dto'
import { PostPreview } from './post-preview'

/**
 *
 * @export
 * @interface GetPostListWithBoardResponseDto
 */
export interface GetPostListWithBoardResponseDto {
  /**
   * 페이징 관련 메타데이터
   * @type {CursorPageMetaResponseDto}
   * @memberof GetPostListWithBoardResponseDto
   */
  meta: CursorPageMetaResponseDto
  /**
   * 게시판 정보
   * @type {BoardInfo}
   * @memberof GetPostListWithBoardResponseDto
   */
  board: BoardInfo
  /**
   * 게시글 목록
   * @type {Array<PostPreview>}
   * @memberof GetPostListWithBoardResponseDto
   */
  data: Array<PostPreview>
}
