/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetBannerImageUrlResponseDto
 */
export interface GetBannerImageUrlResponseDto {
  /**
   * S3에 저장된 배너 이미지 url
   * @type {string}
   * @memberof GetBannerImageUrlResponseDto
   */
  imageUrl: string
}
