/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetTimetableByTimetableIdDto } from './get-timetable-by-timetable-id-dto'

/**
 *
 * @export
 * @interface GetNullableTimetableResponseDto
 */
export interface GetNullableTimetableResponseDto {
  /**
   * 특정 시간표 정보
   * @type {GetTimetableByTimetableIdDto}
   * @memberof GetNullableTimetableResponseDto
   */
  timetable: GetTimetableByTimetableIdDto | null
}
