/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReviewDto } from './review-dto'

/**
 *
 * @export
 * @interface GetCourseReviewsResponseDto
 */
export interface GetCourseReviewsResponseDto {
  /**
   * 총 평점
   * @type {number}
   * @memberof GetCourseReviewsResponseDto
   */
  totalRate: number
  /**
   * 리뷰 개수
   * @type {number}
   * @memberof GetCourseReviewsResponseDto
   */
  reviewCount: number
  /**
   * 리뷰 목록
   * @type {Array<ReviewDto>}
   * @memberof GetCourseReviewsResponseDto
   */
  reviews: Array<ReviewDto>
}
