/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetClubDetailResponseDto
 */
export interface GetClubDetailResponseDto {
  /**
   * club table의 PK
   * @type {number}
   * @memberof GetClubDetailResponseDto
   */
  clubId: number
  /**
   * 동아리명
   * @type {string}
   * @memberof GetClubDetailResponseDto
   */
  name: string
  /**
   * 동아리 카테고리
   * @type {string}
   * @memberof GetClubDetailResponseDto
   */
  category: string
  /**
   * 동아리 요약
   * @type {string}
   * @memberof GetClubDetailResponseDto
   */
  summary: string
  /**
   * 정기 모임
   * @type {string}
   * @memberof GetClubDetailResponseDto
   */
  regularMeeting: string
  /**
   * 모집 기간
   * @type {string}
   * @memberof GetClubDetailResponseDto
   */
  recruitmentPeriod: string
  /**
   * 동아리 설명
   * @type {string}
   * @memberof GetClubDetailResponseDto
   */
  description: string
  /**
   * 동아리 사진 URL 목록
   * @type {Array<string>}
   * @memberof GetClubDetailResponseDto
   */
  imageUrl: Array<string>
  /**
   * 좋아요 개수
   * @type {number}
   * @memberof GetClubDetailResponseDto
   */
  likeCount: number
  /**
   * 인스타그램 링크
   * @type {string}
   * @memberof GetClubDetailResponseDto
   */
  instagramLink?: string
  /**
   * 유튜브 링크
   * @type {string}
   * @memberof GetClubDetailResponseDto
   */
  youtubeLink?: string
  /**
   * 좋아요 여부
   * @type {boolean}
   * @memberof GetClubDetailResponseDto
   */
  isLiked: boolean
  /**
   * 링크 개수
   * @type {number}
   * @memberof GetClubDetailResponseDto
   */
  linkCount: number
}
