/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Character } from './character'

/**
 *
 * @export
 * @interface GetFriendResponseDto
 */
export interface GetFriendResponseDto {
  /**
   * freindship table의 PK
   * @type {number}
   * @memberof GetFriendResponseDto
   */
  friendshipId: number
  /**
   * user table의 PK
   * @type {number}
   * @memberof GetFriendResponseDto
   */
  userId: number
  /**
   * 본명
   * @type {string}
   * @memberof GetFriendResponseDto
   */
  name: string
  /**
   * 친구 추가용 아이디
   * @type {string}
   * @memberof GetFriendResponseDto
   */
  username: string
  /**
   * 출신 학교
   * @type {string}
   * @memberof GetFriendResponseDto
   */
  homeUniversity: string
  /**
   * 전공
   * @type {string}
   * @memberof GetFriendResponseDto
   */
  major: string
  /**
   * 출신 나라
   * @type {string}
   * @memberof GetFriendResponseDto
   */
  country: string
  /**
   * 유저 캐릭터
   * @type {Character}
   * @memberof GetFriendResponseDto
   */
  character: Character
}
