/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetTimetableByUserIdResponseDto
 */
export interface GetTimetableByUserIdResponseDto {
  /**
   * 시간표 ID
   * @type {number}
   * @memberof GetTimetableByUserIdResponseDto
   */
  timetableId: number
  /**
   * 학기
   * @type {string}
   * @memberof GetTimetableByUserIdResponseDto
   */
  semester: string
  /**
   * 연도
   * @type {string}
   * @memberof GetTimetableByUserIdResponseDto
   */
  year: string
  /**
   * 대표 시간표 여부
   * @type {boolean}
   * @memberof GetTimetableByUserIdResponseDto
   */
  mainTimetable: boolean
  /**
   * 시간표 이름
   * @type {string}
   * @memberof GetTimetableByUserIdResponseDto
   */
  timetableName: string
  /**
   * 시간표 색상
   * @type {string}
   * @memberof GetTimetableByUserIdResponseDto
   */
  color: string
}
