/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetReportListResponseDto
 */
export interface GetReportListResponseDto {
  /**
   * 신고 고유 ID
   * @type {number}
   * @memberof GetReportListResponseDto
   */
  id: number
  /**
   * 신고 일시
   * @type {string}
   * @memberof GetReportListResponseDto
   */
  createdAt: string
  /**
   * 신고 사유
   * @type {string}
   * @memberof GetReportListResponseDto
   */
  reason: string
  /**
   * 게시글 신고인지 여부(false 이면 댓글 신고)
   * @type {boolean}
   * @memberof GetReportListResponseDto
   */
  isPost: boolean
}
