/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TodayCourseDto } from './today-course-dto'
import { TodayScheduleDto } from './today-schedule-dto'

/**
 *
 * @export
 * @interface GetTodayTimetableResponse
 */
export interface GetTodayTimetableResponse {
  /**
   * 오늘의 강의 목록
   * @type {Array<TodayCourseDto>}
   * @memberof GetTodayTimetableResponse
   */
  courses?: Array<TodayCourseDto>
  /**
   * 오늘의 일정 목록
   * @type {Array<TodayScheduleDto>}
   * @memberof GetTodayTimetableResponse
   */
  schedules?: Array<TodayScheduleDto>
}
