/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetCourseReviewSummaryResponseDto
 */
export interface GetCourseReviewSummaryResponseDto {
  /**
   * 토탈 평점
   * @type {number}
   * @memberof GetCourseReviewSummaryResponseDto
   */
  totalRate: number
  /**
   * 리뷰 개수
   * @type {number}
   * @memberof GetCourseReviewSummaryResponseDto
   */
  reviewCount: number
  /**
   * 수업 난이도
   * @type {number}
   * @memberof GetCourseReviewSummaryResponseDto
   */
  classLevel: number
  /**
   * 팀 프로젝트 난이도
   * @type {number}
   * @memberof GetCourseReviewSummaryResponseDto
   */
  teamProject: number
  /**
   * 학습량
   * @type {number}
   * @memberof GetCourseReviewSummaryResponseDto
   */
  amountLearned: number
  /**
   * 교수님 강의력
   * @type {number}
   * @memberof GetCourseReviewSummaryResponseDto
   */
  teachingSkills: number
  /**
   * 출석 체크 방식
   * @type {number}
   * @memberof GetCourseReviewSummaryResponseDto
   */
  attendance: number
  /**
   * 강의명
   * @type {string}
   * @memberof GetCourseReviewSummaryResponseDto
   */
  courseName: string
}
