/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetPointHistoryResponseDto
 */
export interface GetPointHistoryResponseDto {
  /**
   * 유형
   * @type {string}
   * @memberof GetPointHistoryResponseDto
   */
  type: string
  /**
   * 일시
   * @type {string}
   * @memberof GetPointHistoryResponseDto
   */
  date: string
  /**
   * 내역
   * @type {string}
   * @memberof GetPointHistoryResponseDto
   */
  history: string
  /**
   * 변경 포인트
   * @type {number}
   * @memberof GetPointHistoryResponseDto
   */
  changePoint: number
  /**
   * 결과 포인트
   * @type {number}
   * @memberof GetPointHistoryResponseDto
   */
  resultPoint: number
}
