/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetProfileResponseDto
 */
export interface GetProfileResponseDto {
  /**
   * 유저아이디
   * @type {string}
   * @memberof GetProfileResponseDto
   */
  username: string
  /**
   * 국적
   * @type {string}
   * @memberof GetProfileResponseDto
   */
  country: string
  /**
   * 모교
   * @type {string}
   * @memberof GetProfileResponseDto
   */
  homeUniversity: string
  /**
   * 전공
   * @type {string}
   * @memberof GetProfileResponseDto
   */
  major: string
  /**
   * 교환학생 시작 날짜
   * @type {string}
   * @memberof GetProfileResponseDto
   */
  startDay: string
  /**
   * 교환학생 끝 날짜
   * @type {string}
   * @memberof GetProfileResponseDto
   */
  endDay: string
  /**
   * 사용 가능한 포인트
   * @type {number}
   * @memberof GetProfileResponseDto
   */
  point: number
  /**
   * 사용 가능 언어 목록
   * @type {Array<string>}
   * @memberof GetProfileResponseDto
   */
  languages: Array<GetProfileResponseDtoLanguages>
  /**
   * 해금된 최대 캐릭터 레벨
   * @type {number}
   * @memberof GetProfileResponseDto
   */
  level: number
  /**
   * 캐릭터 타입
   * @type {string}
   * @memberof GetProfileResponseDto
   */
  type: string
  /**
   * 선택된 캐릭터 레벨
   * @type {number}
   * @memberof GetProfileResponseDto
   */
  selectedLevel: number
}

/**
 * @export
 * @enum {string}
 */
export type GetProfileResponseDtoLanguages =
  | 'abk'
  | 'aar'
  | 'afr'
  | 'aka'
  | 'sqi'
  | 'amh'
  | 'ara'
  | 'arg'
  | 'hye'
  | 'asm'
  | 'ava'
  | 'ave'
  | 'aym'
  | 'aze'
  | 'bam'
  | 'bak'
  | 'eus'
  | 'bel'
  | 'ben'
  | 'bis'
  | 'bos'
  | 'bre'
  | 'bul'
  | 'mya'
  | 'cat'
  | 'cha'
  | 'che'
  | 'nya'
  | 'zho'
  | 'chu'
  | 'chv'
  | 'cor'
  | 'cos'
  | 'cre'
  | 'hrv'
  | 'ces'
  | 'dan'
  | 'div'
  | 'nld'
  | 'dzo'
  | 'eng'
  | 'epo'
  | 'est'
  | 'ewe'
  | 'fao'
  | 'fij'
  | 'fin'
  | 'fra'
  | 'fry'
  | 'ful'
  | 'gla'
  | 'glg'
  | 'lug'
  | 'kat'
  | 'deu'
  | 'ell'
  | 'kal'
  | 'grn'
  | 'guj'
  | 'hat'
  | 'hau'
  | 'heb'
  | 'her'
  | 'hin'
  | 'hmo'
  | 'hun'
  | 'isl'
  | 'ido'
  | 'ibo'
  | 'ind'
  | 'ina'
  | 'ile'
  | 'iku'
  | 'ipk'
  | 'gle'
  | 'ita'
  | 'jpn'
  | 'jav'
  | 'kan'
  | 'kau'
  | 'kas'
  | 'kaz'
  | 'khm'
  | 'kik'
  | 'kin'
  | 'kir'
  | 'kom'
  | 'kon'
  | 'kor'
  | 'kua'
  | 'kur'
  | 'lao'
  | 'lat'
  | 'lav'
  | 'lim'
  | 'lin'
  | 'lit'
  | 'lub'
  | 'ltz'
  | 'mkd'
  | 'mlg'
  | 'msa'
  | 'mal'
  | 'mlt'
  | 'glv'
  | 'mri'
  | 'mar'
  | 'mah'
  | 'mon'
  | 'nau'
  | 'nav'
  | 'nde'
  | 'nbl'
  | 'ndo'
  | 'nep'
  | 'nor'
  | 'nob'
  | 'nno'
  | 'oci'
  | 'oji'
  | 'ori'
  | 'orm'
  | 'oss'
  | 'pli'
  | 'pus'
  | 'fas'
  | 'pol'
  | 'por'
  | 'pan'
  | 'que'
  | 'ron'
  | 'roh'
  | 'run'
  | 'rus'
  | 'sme'
  | 'smo'
  | 'sag'
  | 'san'
  | 'srd'
  | 'srp'
  | 'sna'
  | 'snd'
  | 'sin'
  | 'slk'
  | 'slv'
  | 'som'
  | 'sot'
  | 'spa'
  | 'sun'
  | 'swa'
  | 'ssw'
  | 'swe'
  | 'tgl'
  | 'tah'
  | 'tgk'
  | 'tam'
  | 'tat'
  | 'tel'
  | 'tha'
  | 'bod'
  | 'tir'
  | 'ton'
  | 'tso'
  | 'tsn'
  | 'tur'
  | 'tuk'
  | 'twi'
  | 'uig'
  | 'ukr'
  | 'urd'
  | 'uzb'
  | 'ven'
  | 'vie'
  | 'vol'
  | 'wln'
  | 'cym'
  | 'wol'
  | 'xho'
  | 'iii'
  | 'yid'
  | 'yor'
  | 'zha'
  | 'zul'
