/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Image
 */
export interface Image {
  /**
   * 이미지 고유 ID
   * @type {number}
   * @memberof Image
   */
  id: number
  /**
   * 이미지 경로
   * @type {string}
   * @memberof Image
   */
  imgDir: string
}
