/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LoginRequestDto
 */
export interface LoginRequestDto {
  /**
   * 사용자 이메일
   * @type {string}
   * @memberof LoginRequestDto
   */
  email: string
  /**
   * 사용자 비밀번호
   * @type {string}
   * @memberof LoginRequestDto
   */
  password: string
  /**
   * 로그인 유지 여부
   * @type {boolean}
   * @memberof LoginRequestDto
   */
  keepingLogin: boolean
}
