/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JwtTokenDto } from './jwt-token-dto'

/**
 *
 * @export
 * @interface LoginResponseDto
 */
export interface LoginResponseDto {
  /**
   * JWT 토큰
   * @type {JwtTokenDto}
   * @memberof LoginResponseDto
   */
  token: JwtTokenDto
  /**
   * 학교 인증 여부
   * @type {boolean}
   * @memberof LoginResponseDto
   */
  verified: boolean
  /**
   * 기기 코드
   * @type {string}
   * @memberof LoginResponseDto
   */
  deviceCode: string
  /**
   * 사용자 ID
   * @type {number}
   * @memberof LoginResponseDto
   */
  userId: number
}
