/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LogoutResponseDto
 */
export interface LogoutResponseDto {
  /**
   * 로그아웃 성공 여부
   * @type {boolean}
   * @memberof LogoutResponseDto
   */
  logout: boolean
}
