/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LogoutRequestDto
 */
export interface LogoutRequestDto {
  /**
   * 기기 코드 (없으면 모든 기기 로그아웃)
   * @type {string}
   * @memberof LogoutRequestDto
   */
  deviceCode?: string
}
