/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonCourseResponseDto } from './common-course-response-dto'

/**
 *
 * @export
 * @interface PaginatedCoursesDto
 */
export interface PaginatedCoursesDto {
  /**
   * 다음 페이지 존재 여부
   * @type {boolean}
   * @memberof PaginatedCoursesDto
   */
  hasNextPage: boolean
  /**
   * 다음 cursor id
   * @type {number}
   * @memberof PaginatedCoursesDto
   */
  nextCursorId: number
  /**
   * 강의 리스트
   * @type {Array<CommonCourseResponseDto>}
   * @memberof PaginatedCoursesDto
   */
  data: Array<CommonCourseResponseDto>
}
