/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchCourseReviewsWithKeywordResponse } from './search-course-reviews-with-keyword-response'

/**
 *
 * @export
 * @interface PaginatedCourseReviewsDto
 */
export interface PaginatedCourseReviewsDto {
  /**
   * 다음 페이지 존재 여부
   * @type {boolean}
   * @memberof PaginatedCourseReviewsDto
   */
  hasNextPage: boolean
  /**
   * 다음 cursor id
   * @type {number}
   * @memberof PaginatedCourseReviewsDto
   */
  nextCursorId: number
  /**
   * 강의평 리스트
   * @type {Array<SearchCourseReviewsWithKeywordResponse>}
   * @memberof PaginatedCourseReviewsDto
   */
  data: Array<SearchCourseReviewsWithKeywordResponse>
}
