/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommunityUser } from './community-user'

/**
 *
 * @export
 * @interface PostPreview
 */
export interface PostPreview {
  /**
   * 게시글 고유 ID
   * @type {number}
   * @memberof PostPreview
   */
  id: number
  /**
   * 게시글 제목
   * @type {string}
   * @memberof PostPreview
   */
  title: string
  /**
   * 게시글 내용(100글자 까지)
   * @type {string}
   * @memberof PostPreview
   */
  content: string
  /**
   * 게시글 생성 시간
   * @type {string}
   * @memberof PostPreview
   */
  createdAt: string
  /**
   * 게시글을 생성한 사용자
   * @type {CommunityUser}
   * @memberof PostPreview
   */
  user: CommunityUser
  /**
   * 댓글 수
   * @type {number}
   * @memberof PostPreview
   */
  commentCount: number
  /**
   * 스크랩 수
   * @type {number}
   * @memberof PostPreview
   */
  scrapCount: number
  /**
   * 스크랩 여부
   * @type {boolean}
   * @memberof PostPreview
   */
  myScrap: boolean
  /**
   * 사진 미리보기(사진이 없으면 null)
   * @type {string}
   * @memberof PostPreview
   */
  thumbnailDir: string
  /**
   * 반응 수
   * @type {number}
   * @memberof PostPreview
   */
  reactionCount: number
  /**
   * 조회 수
   * @type {number}
   * @memberof PostPreview
   */
  views: number
}
