/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PurchaseItemResponseDto
 */
export interface PurchaseItemResponseDto {
  /**
   * 업데이트된 열람 가능 기간 (강의평 열람권 구매 시)
   * @type {string}
   * @memberof PurchaseItemResponseDto
   */
  viewableUntil?: string
  /**
   * 업그레이드 레벨 (캐릭터 진화 구매 시)
   * @type {number}
   * @memberof PurchaseItemResponseDto
   */
  upgradeLevel?: number
  /**
   * 변경된 캐릭터 타입 (캐릭터 타입 변경 구매 시)
   * @type {string}
   * @memberof PurchaseItemResponseDto
   */
  newCharacterType?: string
}
