/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PurchaseItemRequestDto
 */
export interface PurchaseItemRequestDto {
  /**
   * 요구 포인트
   * @type {number}
   * @memberof PurchaseItemRequestDto
   */
  requiredPoints: number
  /**
   * 아이템 카테고리
   * @type {string}
   * @memberof PurchaseItemRequestDto
   */
  itemCategory: PurchaseItemRequestDtoItemCategory
  /**
   * 열람 일수 (강의평 열람권 구매 시에만)
   * @type {number}
   * @memberof PurchaseItemRequestDto
   */
  days?: PurchaseItemRequestDtoDays
}

/**
 * @export
 * @enum {string}
 */
export type PurchaseItemRequestDtoItemCategory =
  | 'COURSE_REVIEW_READING_TICKET'
  | 'CHARACTER_EVOLUTION'
  | 'CHARACTER_TYPE_CHANGE'
/**
 * @export
 * @enum {string}
 */
export type PurchaseItemRequestDtoDays = 3 | 7 | 30
