/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ReactionCount
 */
export interface ReactionCount {
  /**
   * 좋아요
   * @type {number}
   * @memberof ReactionCount
   */
  good: number
  /**
   * 슬퍼요
   * @type {number}
   * @memberof ReactionCount
   */
  sad: number
  /**
   * 놀라워요
   * @type {number}
   * @memberof ReactionCount
   */
  amazing: number
  /**
   * 화나요
   * @type {number}
   * @memberof ReactionCount
   */
  angry: number
  /**
   * 웃겨요
   * @type {number}
   * @memberof ReactionCount
   */
  funny: number
}
