/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ReactPostRequestDto
 */
export interface ReactPostRequestDto {
  /**
   * 남길 반응 종류
   * @type {number}
   * @memberof ReactPostRequestDto
   */
  reaction: ReactPostRequestDtoReaction
}

/**
 * @export
 * @enum {string}
 */
export type ReactPostRequestDtoReaction = 0 | 1 | 2 | 3 | 4
