/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ReportedPost
 */
export interface ReportedPost {
  /**
   * 게시글 고유 ID
   * @type {number}
   * @memberof ReportedPost
   */
  id: number
  /**
   * 게시글 제목
   * @type {string}
   * @memberof ReportedPost
   */
  title: string
  /**
   * 게시글 내용
   * @type {string}
   * @memberof ReportedPost
   */
  content: string
  /**
   * 게시글 첨부 이미지
   * @type {Array<string>}
   * @memberof ReportedPost
   */
  imgDirs: Array<string>
}
