/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ReportedComment
 */
export interface ReportedComment {
  /**
   * 댓글 고유 ID
   * @type {number}
   * @memberof ReportedComment
   */
  id: number
  /**
   * 댓글 내용
   * @type {string}
   * @memberof ReportedComment
   */
  content: string
}
