/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ReportedUser
 */
export interface ReportedUser {
  /**
   * 사용자 고유 ID
   * @type {number}
   * @memberof ReportedUser
   */
  id: number
  /**
   * 사용자 username
   * @type {string}
   * @memberof ReportedUser
   */
  username: string
}
