/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ReviewDto
 */
export interface ReviewDto {
  /**
   * 강의평 ID
   * @type {number}
   * @memberof ReviewDto
   */
  id: number
  /**
   * 평점
   * @type {number}
   * @memberof ReviewDto
   */
  rate: number
  /**
   * 작성 일시
   * @type {string}
   * @memberof ReviewDto
   */
  createdAt: string
  /**
   * 작성자
   * @type {string}
   * @memberof ReviewDto
   */
  reviewer: string
  /**
   * 연도
   * @type {string}
   * @memberof ReviewDto
   */
  year: string
  /**
   * 학기
   * @type {string}
   * @memberof ReviewDto
   */
  semester: string
  /**
   * 추천 여부
   * @type {boolean}
   * @memberof ReviewDto
   */
  myRecommend: boolean
  /**
   * 추천수
   * @type {number}
   * @memberof ReviewDto
   */
  recommendCount: number
  /**
   * 강의평 텍스트
   * @type {string}
   * @memberof ReviewDto
   */
  text: string
  /**
   * 수업 난이도
   * @type {number}
   * @memberof ReviewDto
   */
  classLevel: number
  /**
   * 팀 프로젝트 난이도
   * @type {number}
   * @memberof ReviewDto
   */
  teamProject: number
  /**
   * 학습량
   * @type {number}
   * @memberof ReviewDto
   */
  amountLearned: number
  /**
   * 교수님 강의력
   * @type {number}
   * @memberof ReviewDto
   */
  teachingSkills: number
  /**
   * 출석 체크 방식
   * @type {number}
   * @memberof ReviewDto
   */
  attendance: number
}
