/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SearchCourseReviewsWithKeywordResponse
 */
export interface SearchCourseReviewsWithKeywordResponse {
  /**
   * 리뷰 id
   * @type {number}
   * @memberof SearchCourseReviewsWithKeywordResponse
   */
  id: number
  /**
   * 총 평점
   * @type {number}
   * @memberof SearchCourseReviewsWithKeywordResponse
   */
  totalRate: number
  /**
   * 리뷰 개수
   * @type {number}
   * @memberof SearchCourseReviewsWithKeywordResponse
   */
  reviewCount: number
  /**
   * 과목명
   * @type {string}
   * @memberof SearchCourseReviewsWithKeywordResponse
   */
  courseName: string
  /**
   * 교수명
   * @type {string}
   * @memberof SearchCourseReviewsWithKeywordResponse
   */
  professorName: string
}
