/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SendTempPasswordRequestDto
 */
export interface SendTempPasswordRequestDto {
  /**
   * 임시비밀번호를 발급받고자 하는 계정의 이메일
   * @type {string}
   * @memberof SendTempPasswordRequestDto
   */
  email: string
}
