/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SetExchangeDayReqeustDto
 */
export interface SetExchangeDayReqeustDto {
  /**
   * 교환학생 시작 날짜
   * @type {string}
   * @memberof SetExchangeDayReqeustDto
   */
  startDay: string
  /**
   * 교환학생 끝 날짜
   * @type {string}
   * @memberof SetExchangeDayReqeustDto
   */
  endDay: string
}
