/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SetProfileRequestDto
 */
export interface SetProfileRequestDto {
  /**
   * 유저아이디
   * @type {string}
   * @memberof SetProfileRequestDto
   */
  username: string
  /**
   * 국적
   * @type {string}
   * @memberof SetProfileRequestDto
   */
  country: string
  /**
   * 모교
   * @type {string}
   * @memberof SetProfileRequestDto
   */
  homeUniversity: string
  /**
   * 전공
   * @type {string}
   * @memberof SetProfileRequestDto
   */
  major: string
}
