/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SignUpResponseDto
 */
export interface SignUpResponseDto {
  /**
   * 학교인증요청 성공 여부
   * @type {boolean}
   * @memberof SignUpResponseDto
   */
  sended: boolean
  /**
   * 인증요청한 학번
   * @type {number}
   * @memberof SignUpResponseDto
   */
  studentNumber: number
}
