/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TakeAttendanceResponseDto
 */
export interface TakeAttendanceResponseDto {
  /**
   * 출석자 ID
   * @type {number}
   * @memberof TakeAttendanceResponseDto
   */
  userId: number
  /**
   * 출석 날짜
   * @type {string}
   * @memberof TakeAttendanceResponseDto
   */
  attendanceDate: string
  /**
   * 출석 성공 여부
   * @type {boolean}
   * @memberof TakeAttendanceResponseDto
   */
  success: boolean
}
