/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TimetableDto
 */
export interface TimetableDto {
  /**
   * 학기
   * @type {string}
   * @memberof TimetableDto
   */
  semester: string
  /**
   * 연도
   * @type {string}
   * @memberof TimetableDto
   */
  year: string
}
