/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TodayScheduleDto
 */
export interface TodayScheduleDto {
  /**
   * 일정 이름
   * @type {string}
   * @memberof TodayScheduleDto
   */
  scheduleName: string
  /**
   * 시작 시간
   * @type {string}
   * @memberof TodayScheduleDto
   */
  startTime: string
  /**
   * 종료 시간
   * @type {string}
   * @memberof TodayScheduleDto
   */
  endTime: string
  /**
   * 위치
   * @type {string}
   * @memberof TodayScheduleDto
   */
  location?: string
}
