/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateScheduleResponseDto
 */
export interface UpdateScheduleResponseDto {
  /**
   * ID
   * @type {number}
   * @memberof UpdateScheduleResponseDto
   */
  id: number
  /**
   * 시간표 ID
   * @type {number}
   * @memberof UpdateScheduleResponseDto
   */
  timetableId: number
  /**
   * 일정 이름
   * @type {string}
   * @memberof UpdateScheduleResponseDto
   */
  title: string
  /**
   * 요일
   * @type {string}
   * @memberof UpdateScheduleResponseDto
   */
  day: string
  /**
   * 시작 시간
   * @type {string}
   * @memberof UpdateScheduleResponseDto
   */
  startTime: string
  /**
   * 종료 시간
   * @type {string}
   * @memberof UpdateScheduleResponseDto
   */
  endTime: string
  /**
   * 장소
   * @type {string}
   * @memberof UpdateScheduleResponseDto
   */
  location: string
}
