/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateCalendarDataRequestDto
 */
export interface UpdateCalendarDataRequestDto {
  /**
   * 시작 날짜 (AAAA-BB-CC 형식)
   * @type {string}
   * @memberof UpdateCalendarDataRequestDto
   */
  startDate?: string
  /**
   * 종료 날짜 (AAAA-BB-CC 형식)
   * @type {string}
   * @memberof UpdateCalendarDataRequestDto
   */
  endDate?: string
  /**
   * 행사/일정 제목
   * @type {string}
   * @memberof UpdateCalendarDataRequestDto
   */
  title?: string
  /**
   * 행사/일정 설명
   * @type {string}
   * @memberof UpdateCalendarDataRequestDto
   */
  description?: string
  /**
   * 학사 일정 여부
   * @type {boolean}
   * @memberof UpdateCalendarDataRequestDto
   */
  isAcademic?: boolean
}
