/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateCommentRequestDto
 */
export interface UpdateCommentRequestDto {
  /**
   * 댓글 내용
   * @type {string}
   * @memberof UpdateCommentRequestDto
   */
  content: string
  /**
   * 익명 여부
   * @type {boolean}
   * @memberof UpdateCommentRequestDto
   */
  isAnonymous: boolean
}
