/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateScheduleRequestDto
 */
export interface UpdateScheduleRequestDto {
  /**
   * 시간표 ID
   * @type {number}
   * @memberof UpdateScheduleRequestDto
   */
  timetableId: number
  /**
   * 일정 이름
   * @type {string}
   * @memberof UpdateScheduleRequestDto
   */
  title?: string
  /**
   * 요일
   * @type {string}
   * @memberof UpdateScheduleRequestDto
   */
  day?: string
  /**
   * 시작 시간
   * @type {string}
   * @memberof UpdateScheduleRequestDto
   */
  startTime?: string
  /**
   * 종료 시간
   * @type {string}
   * @memberof UpdateScheduleRequestDto
   */
  endTime?: string
  /**
   * 장소
   * @type {string}
   * @memberof UpdateScheduleRequestDto
   */
  location?: string
}
