/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface VerificationRequestDto
 */
export interface VerificationRequestDto {
  /**
   * 사용자 이메일
   * @type {string}
   * @memberof VerificationRequestDto
   */
  email: string
}
