/* tslint:disable */
/* eslint-disable */
/**
 * KU-KEY API
 * API for KU-KEY service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * as AttendanceCheckApi from './api/attendance-check-api'
export * as AuthApi from './api/auth-api'
export * as BoardApi from './api/board-api'
export * as CalendarApi from './api/calendar-api'
export * as ClubApi from './api/club-api'
export * as CommentApi from './api/comment-api'
export * as CourseApi from './api/course-api'
export * as CourseReviewApi from './api/course-review-api'
export * as DefaultApi from './api/default-api'
export * as FriendshipApi from './api/friendship-api'
export * as NoticeApi from './api/notice-api'
export * as PostApi from './api/post-api'
export * as ReportApi from './api/report-api'
export * as ScheduleApi from './api/schedule-api'
export * as TimetableApi from './api/timetable-api'
export * as UserApi from './api/user-api'
