name: Auto Create Deploy PR

on:
  push:
    branches: ['dev', 'test-auto-deploy']

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        run: gh pr create -B dev -H test-auto-deploy --title 'Deploy test-auto-deploy' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
